// jshint esversion:6
const selectedCardActionTypes = {
    SELECT_CARD: 'SELECT_CARD',
    UNSELECT_CARD: 'UNSELECT_CARD',
    SELECT_CARD_INFO: 'SELECT_CARD_INFO',
    ALLOW_DISCARD: 'ALLOW_DISCARD',
    DISALLOW_DISCARD: 'DISALLOW_DISCARD',
    ALLOW_TRADE: 'ALLOW_TRADE',
    DISALLOW_TRADE: 'DISALLOW_TRADE',
    TOGGLE_TRADE_HUD: 'TOGGLE_TRADE_HUD',
    TOGGLE_TRADE_FOR: 'TOGGLE_TRADE_FOR',
    SET_TRADE_TARGET: 'SET_TRADE_TARGET',
    TOGGLE_TARGETABLE: 'TOGGLE_TARGETABLE',
    TOGGLE_NICE_SHOT: 'TOGGLE_NICE_SHOT',
    TOGGLE_MISSING: 'TOGGLE_MISSING'
};

export default selectedCardActionTypes;