// jshint esversion:6
const playerActionTypes = {
    RETRIEVE_PLAYERS: 'RETRIEVE_PLAYERS',
    ADD_PLAYER: 'ADD_PLAYER',
    UPDATE_PLAYER_NAME: 'UPDATE_PLAYER_NAME',
    UPDATE_PLAYER_CARDS: 'UPDATE_PLAYER_CARDS',
    UPDATE_PLAYER_SCORE: 'UPDATE_PLAYER_SCORE',
    REMOVE_PLAYER: 'REMOVE_PLAYER',
    CLEAR_PLAYER_DATA: 'CLEAR_PLAYER_DATA'
};

export default playerActionTypes;