// jshint esversion:6
const playerActionTypes = {
    RETRIEVE_PLAYERS: 'RETRIEVE_PLAYERS',
    ADD_PLAYER: 'ADD_PLAYER',
    UPDATE_PLAYER_NAME: 'UPDATE_PLAYER_NAME',
    UPDATE_PLAYER_CARDS: 'UPDATE_PLAYER_CARDS',
    UPDATE_PLAYER_SCORE: 'UPDATE_PLAYER_SCORE',
    LOG_OUT_PLAYER: 'LOG_OUT_PLAYER',
    REMOVE_PLAYER: 'REMOVE_PLAYER',
    CLEAR_PLAYER_DATA: 'CLEAR_PLAYER_DATA',
    SET_PLAYER_TURN_ACTIVE: 'SET_PLAYER_TURN_ACTIVE',
    SET_PLAYER_TURN_INACTIVE: 'SET_PLAYER_TURN_INACTIVE',
};

export default playerActionTypes;